#!/bin/bash

HOST_SPEC_DIR=$PWD
CONT_SPEC_DIR=/opt/citac/var/specs/$(basename $PWD)

if [ $1 = "adv" ]; then
    shift
    CITAC_ARGS="$@"
else
    CITAC_ARGS="simple $@"
fi

docker run \
    --rm \
    --privileged \
    -v /tmp:/tmp:rw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v ${HOST_SPEC_DIR}:${CONT_SPEC_DIR}:rw \
    -w ${CONT_SPEC_DIR} \
    citac/environments:main \
    citac ${CITAC_ARGS}