#!/bin/bash

if [ $(whoami) != "root" ]; then
    echo "Please run as root."
    exit 1
fi

HOST_SPEC_DIR=$PWD
CONT_SPEC_DIR=/var/citac/specs/$(basename $PWD)

if [ $1 = "adv" ]; then
    shift
    CITAC_ARGS="$@"
else
    CITAC_ARGS="simple $@"
fi

docker run \
    --rm \
    --privileged \
    -v /usr/bin/docker:/usr/bin/docker:ro \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1:ro \
    -v ${HOST_SPEC_DIR}:${CONT_SPEC_DIR}:rw \
    citac \
    citac ${CITAC_ARGS}